  - name: Remove previous results
    shell: rm -rf /opt/openstack-testing/allure-results
    
  - name: Start N01
    ansible.builtin.shell: npx playwright test N01 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    register: results
    ignore_errors: true
  - debug: msg="Tests finished"

  - name: Start N02
    ansible.builtin.shell: npx playwright test N02 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    register: results
    ignore_errors: true
  - debug: msg="Tests finished"

  - name: Start N03
    ansible.builtin.shell: npx playwright test N03 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="Tests finished"
  
  - name: Start N04
    ansible.builtin.shell: npx playwright test N04 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    register: results
    ignore_errors: true
  - debug: msg="Tests finished"
  
  - name: Start N05
    ansible.builtin.shell: npx playwright test N05 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    register: results
    ignore_errors: true
  - debug: msg="Tests finished"

  - name: Start N06
    ansible.builtin.shell: npx playwright test N06 >> /tmp/running-test.log  
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="Tests finished"
  
  - name: Start N07
    ansible.builtin.shell: npx playwright test N07 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="Tests finished"
  
  - name: Start N08
    ansible.builtin.shell: npx playwright test N08 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="Tests finished"
  
  - name: Start N09
    ansible.builtin.shell: npx playwright test N09 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="Tests finished"
    
  - name: Start N10
    ansible.builtin.shell: npx playwright test N10 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="Tests finished"
 
  - name: Start N11
    ansible.builtin.shell: npx playwright test N11 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="Tests finished"
  
  - name: Start N12
    ansible.builtin.shell: npx playwright test N12 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="Tests finished"
  
  - name: Start N13
    ansible.builtin.shell: npx playwright test N13 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="Tests finished"

  - name: Start N14
    ansible.builtin.shell: npx playwright test N14 >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="Tests finished"
  
  - name: Allure generate results
    args:
      chdir: /opt/openstack-testing
    shell: |
      PATH=/opt/openstack-testing/allure-2.21.0/bin/:$PATH
      allure generate allure-results --clean
    register: results
  - debug:
      var: results.stdout_lines
        
  - name: Allure generate report
    args:
      chdir: /opt/openstack-testing
    shell: |
      PATH=/opt/openstack-testing/allure-2.21.0/bin/:$PATH
      node ./node_modules/allure-single-html-file-js/combine.js ./allure-report

  - name: Allure open allure-report
    args:
      chdir: /opt/openstack-testing
    shell: |
      PATH=/opt/openstack-testing/allure-2.21.0/bin/:$PATH
      nohup allure serve -p 32300 &
