  - name: Start T01 Administration - Cloud Service Tests
    ansible.builtin.shell: npx playwright test ./tests/T01.spec.ts >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    register: results
    ignore_errors: true
  - debug: msg="T01 Administration - Cloud Service Tests finished"
  
  - name: Start T02 NFVI Co-Deployment Infra level Capability Verification 
    ansible.builtin.shell: npx playwright test ./tests/T02.spec.ts >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    register: results
    ignore_errors: true
  - debug: msg="T02 NFVI Co-Deployment Infra level Capability Verification  Tests finished"
      
  - name: Start T03 Administration - Compute / Storage Tests
    ansible.builtin.shell: npx playwright test ./tests/T03.spec.ts >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="T03 Administration - Compute / Storage Tests finished"

  - name: Start T06 Openstack Nodes Functionality Tests
    ansible.builtin.shell: npx playwright test ./tests/T06.spec.ts >> /tmp/running-test.log  
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="T06 Openstack Nodes Functionality Tests finished"
      
  - name: Start T07 RHOSP Version Tests
    ansible.builtin.shell: npx playwright test ./tests/T07.spec.ts >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    ignore_errors: true
  - debug: msg="T07 RHOSP Version Tests finished"
      
  - name: Start T04 Infrastructure-Virtual Resources Tests
    ansible.builtin.shell: npx playwright test ./tests/T04.spec.ts >> /tmp/running-test.log
    args:
      chdir: /opt/openstack-testing
    register: results
    ignore_errors: true
  - debug: msg="T04 Infrastructure-Virtual Resources Tests finished"
    
  - name: Allure generate results
    args:
      chdir: /opt/openstack-testing
    shell: |
      PATH=/opt/openstack-testing/allure-2.21.0/bin/:$PATH
      allure generate allure-results --clean
    register: results
  - debug:
      var: results.stdout_lines
        
  - name: Allure generate report
    args:
      chdir: /opt/openstack-testing
    shell: |
      PATH=/opt/openstack-testing/allure-2.21.0/bin/:$PATH
      node ./node_modules/allure-single-html-file-js/combine.js ./allure-report

  - name: Allure open allure-report
    args:
      chdir: /opt/openstack-testing
    shell: |
      PATH=/opt/openstack-testing/allure-2.21.0/bin/:$PATH
      nohup allure serve -p 32300 &
